<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVjp6rps\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVjp6rps/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVjp6rps.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVjp6rps\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVjp6rps\App_KernelDevDebugContainer([
    'container.build_hash' => 'Vjp6rps',
    'container.build_id' => '9c5c2aff',
    'container.build_time' => 1635529705,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVjp6rps');
