<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerS8EyymH\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerS8EyymH/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerS8EyymH.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerS8EyymH\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerS8EyymH\App_KernelDevDebugContainer([
    'container.build_hash' => 'S8EyymH',
    'container.build_id' => 'cfb19104',
    'container.build_time' => 1635513128,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerS8EyymH');
