<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYFYZ8Ni\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYFYZ8Ni/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYFYZ8Ni.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYFYZ8Ni\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYFYZ8Ni\App_KernelDevDebugContainer([
    'container.build_hash' => 'YFYZ8Ni',
    'container.build_id' => 'd1f393bf',
    'container.build_time' => 1635460934,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYFYZ8Ni');
