<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'add_product' => [[], ['_controller' => 'App\\Controller\\ProductController::add'], [], [['text', '/v1/products']], [], []],
    'get_all_products' => [[], ['_controller' => 'App\\Controller\\ProductController::getAll'], [], [['text', '/v1/products']], [], []],
    'get_product_by_id' => [['id'], ['_controller' => 'App\\Controller\\ProductController::getById'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/v1/products']], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
];
